language: node_js
node_js:
 - "0.11"
 - "0.10"
 - "0.8"
 - "0.6"
 - iojs

after_success: 
 - npm install -g istanbul
 - npm install coveralls
 - istanbul cover node_modules/.bin/_mocha --report lcovonly -- -R spec
 - echo ./coverage/lcov.info
 - (cat ./coverage/lcov.info | ./node_modules/.bin/coveralls) || true
 - rm -rf ./coverage